
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Stepper motor - yaw controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: yaw_joint_l1
  pid: {p: 10, i: 0.1, d: 1}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: yaw_joint_l2
  pid: {p: 10, i: 0.1, d: 1}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: yaw_joint_r1
  pid: {p: 10, i: 0.1, d: 1}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: yaw_joint_r2
  pid: {p: 10, i: 0.1, d: 1}


# DC motor - drive controllers ---------------------------------------
joint5_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: drive_joint_l1
  pid: {p: 10, i: 0.1, d: 0}
joint6_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: drive_joint_l2
  pid: {p: 10, i: 0.1, d: 0}
joint7_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: drive_joint_r1
  pid: {p: 10, i: 0.1, d: 0}
joint8_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: drive_joint_r2
  pid: {p: 10, i: 0.1, d: 0}
